timeout: 3

/AWEOS Installation ISO Environment
    protocol: linux
    kernel_path: boot():/boot/bzImage
    module_path: boot():/boot/aweos-initramfs.cpio.gz
    cmdline: aweos.mode=installer console=tty0 console=ttyS0,115200n8 quiet
