# AWEOS x86_64 Limine configuration
# Linux kernel source remains isolated in /linux and is never modified by boot tooling.
TIMEOUT=5

:AWEOS Linux x86_64
    PROTOCOL=linux
    KERNEL_PATH=boot:///boot/bzImage
    CMDLINE=quiet loglevel=4
